name: ArtifactHub Linter

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'

      - name: Copy changed services to new directory
        run: mkdir changed_services && cp -pv --parents $(git diff --name-only) changed_services
      
      - name: Download ArtifactHUB CLI
        working-directory: ./changed_services
        run: |
          wget https://github.com/artifacthub/hub/releases/download/v1.6.0/ah_1.6.0_linux_amd64.tar.gz
          tar -xvf ah_1.6.0_linux_amd64.tar.gz
      
      - name: Run linter
        working-directory: ./changed_services
        run: ./ah lint --kind keptn .