name: ArtifactHub Linter

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done

      #- name: Setup Go environment
      #  uses: actions/setup-go@v2
      #  with:
      #    go-version: '^1.13.1'
      
      #- name: Download ArtifactHUB CLI
      #  run: |
      #    wget https://github.com/artifacthub/hub/releases/download/v1.4.0/ah_1.4.0_linux_amd64.tar.gz
      #    tar -xvf ah_1.4.0_linux_amd64.tar.gz
      
      #- name: Run linter
      #  run: ./ah lint --kind keptn .
