name: ArtifactHub Linter

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - id: files
        uses: Ana06/get-changed-files@v2.1.0
      - run: |
          mkdir changed_services && cp -pv --parents ${{ steps.files.outputs.all }} changed_services
      
      - name: Download ArtifactHUB CLI
        working-directory: ./changed_services
        run: |
          wget https://github.com/artifacthub/hub/releases/download/v1.6.0/ah_1.6.0_linux_amd64.tar.gz
          tar -xvf ah_1.6.0_linux_amd64.tar.gz
      
      - name: Run linter
        id: run_linter
        working-directory: ./changed_services
        run: | 
          OUTPUT=$(./ah lint --kind keptn . || true )
          OUTPUT="${OUTPUT//'%'/'%25'}​【7,6 m】"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=output::$OUTPUT"
          
          ./ah lint --kind keptn .

      - name: Send PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: always() && github.event_name == 'pull_request'
        with:
          header: Lint result
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            AH Linter output: ${{ steps.run_linter.outputs.output }}